# Generated by Django 2.0.3 on 2018-08-12 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='site',
            field=models.CharField(default='', max_length=255),
        ),
    ]
